name: Build Moshi Kotlin Codegen Plugin

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Assemble plugin
        run: ./gradlew :moshi-kotlin-codegen:assemble --stacktrace

      - name: Prepare plugin artifact
        run: |
          mkdir -p artifacts
          for file in moshi-kotlin-codegen/build/libs/*.jar; do
            if [[ "${file}" != *-sources.jar ]]; then
              cp "${file}" artifacts/
            fi
          done

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: moshi-kotlin-codegen-plugin
          path: artifacts/*.jar

      - name: Upload release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
